[project]
name = "vault"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pulumi>=3.181.0",
    "pulumi-kubernetes>=4.23.0",
    "pulumi-tls>=5.2.0",
]
