# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_kuberay_crds.meta as __meta
    meta = __meta
    import pulumi_kuberay_crds.ray as __ray
    ray = __ray
else:
    meta = _utilities.lazy_import('pulumi_kuberay_crds.meta')
    ray = _utilities.lazy_import('pulumi_kuberay_crds.ray')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "kuberay_crds",
  "mod": "ray.io/v1",
  "fqn": "pulumi_kuberay_crds.ray.v1",
  "classes": {
   "kubernetes:ray.io/v1:RayCluster": "RayCluster",
   "kubernetes:ray.io/v1:RayClusterList": "RayClusterList",
   "kubernetes:ray.io/v1:RayClusterPatch": "RayClusterPatch"
  }
 },
 {
  "pkg": "kuberay_crds",
  "mod": "ray.io/v1alpha1",
  "fqn": "pulumi_kuberay_crds.ray.v1alpha1",
  "classes": {
   "kubernetes:ray.io/v1alpha1:RayCluster": "RayCluster",
   "kubernetes:ray.io/v1alpha1:RayClusterList": "RayClusterList",
   "kubernetes:ray.io/v1alpha1:RayClusterPatch": "RayClusterPatch"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "kuberay_crds",
  "token": "pulumi:providers:kubernetes",
  "fqn": "pulumi_kuberay_crds",
  "class": "Provider"
 }
]
"""
)
