# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from .. import _utilities
import typing

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_mysql_operator_crds.mysql.v2 as __v2
    v2 = __v2
else:
    v2 = _utilities.lazy_import('pulumi_mysql_operator_crds.mysql.v2')
