[project]
name = "golink"
version = "0.1.0"
description = "Modal deployment for Tailscale golink service"
dependencies = [
    "modal",
]
requires-python = ">=3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"