{
 "title": "Serve Deployment Dashboard",
 "tags": [ "rayVersion:2.52.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Application",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{}, application)"
    }
   },
   {
    "name": "Deployment",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{application=~\"$Application\",}, deployment)"
    }
   },
   {
    "name": "Replica",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{application=~\"$Application\",deployment=~\"$Deployment\",}, replica)"
    }
   },
   {
    "name": "Route",
    "query": {
     "query": "label_values(ray_serve_deployment_request_counter{deployment=~\"$Deployment\",}, route)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(ray_node_network_receive_speed{}, ray_io_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Replicas per deployment",
   "type": "graph",
   "description": "Number of replicas per deployment. Ignores \"Route\" variable.",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_replica_healthy{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}) by (application, deployment)",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    }
   ]
  },
  {
   "title": "QPS per replica",
   "type": "graph",
   "description": "QPS for each replica.",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_request_counter_total{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, deployment, replica)",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    }
   ]
  },
  {
   "title": "Error QPS per replica",
   "type": "graph",
   "description": "Error QPS for each replica.",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_error_counter_total{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, deployment, replica)",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    }
   ]
  },
  {
   "title": "P50 latency per replica",
   "type": "graph",
   "description": "P50 latency per replica.",
   "gridPos": { "x": 0, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P90 latency per replica",
   "type": "graph",
   "description": "P90 latency per replica.",
   "gridPos": { "x": 8, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P99 latency per replica",
   "type": "graph",
   "description": "P99 latency per replica.",
   "gridPos": { "x": 16, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Queue size per deployment",
   "type": "graph",
   "description": "Number of requests queued per deployment. Ignores \"Replica\" and \"Route\" variable.",
   "gridPos": { "x": 0, "y": 2, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_queued_queries{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}) by (application, deployment)",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    }
   ]
  },
  {
   "title": "Running requests per replica",
   "type": "graph",
   "description": "Current running requests for each replica.",
   "gridPos": { "x": 12, "y": 2, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_replica_processing_queries{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}) by (application, deployment, replica)",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    }
   ]
  },
  {
   "title": "Multiplexed models per replica",
   "type": "graph",
   "description": "The number of multiplexed models for each replica.",
   "gridPos": { "x": 0, "y": 3, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "models" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_num_multiplexed_models{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}) by (application, deployment, replica)",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    }
   ]
  },
  {
   "title": "Multiplexed model loads per replica",
   "type": "graph",
   "description": "The number of times of multiplexed models loaded for each replica.",
   "gridPos": { "x": 8, "y": 3, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "times" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_multiplexed_models_load_counter_total{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}) by (application, deployment, replica)",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    }
   ]
  },
  {
   "title": "Multiplexed model unloads per replica",
   "type": "graph",
   "description": "The number of times of multiplexed models unloaded for each replica.",
   "gridPos": { "x": 16, "y": 3, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "times" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_multiplexed_models_unload_counter_total{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}) by (application, deployment, replica)",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    }
   ]
  },
  {
   "title": "P99 latency of multiplexed model loads per replica",
   "type": "graph",
   "description": "P99 latency of multiplexed model load per replica.",
   "gridPos": { "x": 0, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_multiplexed_model_load_latency_ms_bucket{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    }
   ]
  },
  {
   "title": "P99 latency of multiplexed model unloads per replica",
   "type": "graph",
   "description": "P99 latency of multiplexed model unload per replica.",
   "gridPos": { "x": 8, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_multiplexed_model_unload_latency_ms_bucket{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    }
   ]
  },
  {
   "title": "Multiplexed model ids per replica",
   "type": "graph",
   "description": "The ids of multiplexed models for each replica.",
   "gridPos": { "x": 16, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "model" }
   ],
   "targets": [
    {
     "expr": "ray_serve_registered_multiplexed_model_id{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}",
     "legendFormat": "{{replica}}:{{model_id}}"
    }
   ]
  },
  {
   "title": "Multiplexed model cache hit rate",
   "type": "graph",
   "description": "The cache hit rate of multiplexed models for the deployment.",
   "gridPos": { "x": 0, "y": 5, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(rate(ray_serve_multiplexed_models_load_counter_total{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}[5m]))/sum(rate(ray_serve_multiplexed_get_model_requests_counter_total{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\"}[5m])))",
     "legendFormat": "{{application}}#{{deployment}}#{{replica}}"
    }
   ]
  }
 ]
}