# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_clickhouse_operator_crds.clickhouse as __clickhouse
    clickhouse = __clickhouse
    import pulumi_clickhouse_operator_crds.meta as __meta
    meta = __meta
else:
    clickhouse = _utilities.lazy_import('pulumi_clickhouse_operator_crds.clickhouse')
    meta = _utilities.lazy_import('pulumi_clickhouse_operator_crds.meta')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "clickhouse_operator_crds",
  "mod": "clickhouse.altinity.com/v1",
  "fqn": "pulumi_clickhouse_operator_crds.clickhouse.v1",
  "classes": {
   "kubernetes:clickhouse.altinity.com/v1:ClickHouseInstallation": "ClickHouseInstallation",
   "kubernetes:clickhouse.altinity.com/v1:ClickHouseInstallationList": "ClickHouseInstallationList",
   "kubernetes:clickhouse.altinity.com/v1:ClickHouseInstallationPatch": "ClickHouseInstallationPatch"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "clickhouse_operator_crds",
  "token": "pulumi:providers:kubernetes",
  "fqn": "pulumi_clickhouse_operator_crds",
  "class": "Provider"
 }
]
"""
)
