# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_mysql_operator_crds.meta as __meta
    meta = __meta
    import pulumi_mysql_operator_crds.mysql as __mysql
    mysql = __mysql
    import pulumi_mysql_operator_crds.zalando as __zalando
    zalando = __zalando
else:
    meta = _utilities.lazy_import('pulumi_mysql_operator_crds.meta')
    mysql = _utilities.lazy_import('pulumi_mysql_operator_crds.mysql')
    zalando = _utilities.lazy_import('pulumi_mysql_operator_crds.zalando')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "mysql_operator_crds",
  "mod": "mysql.oracle.com/v2",
  "fqn": "pulumi_mysql_operator_crds.mysql.v2",
  "classes": {
   "kubernetes:mysql.oracle.com/v2:InnoDBCluster": "InnoDBCluster",
   "kubernetes:mysql.oracle.com/v2:InnoDBClusterList": "InnoDBClusterList",
   "kubernetes:mysql.oracle.com/v2:InnoDBClusterPatch": "InnoDBClusterPatch",
   "kubernetes:mysql.oracle.com/v2:MySQLBackup": "MySQLBackup",
   "kubernetes:mysql.oracle.com/v2:MySQLBackupList": "MySQLBackupList",
   "kubernetes:mysql.oracle.com/v2:MySQLBackupPatch": "MySQLBackupPatch"
  }
 },
 {
  "pkg": "mysql_operator_crds",
  "mod": "zalando.org/v1",
  "fqn": "pulumi_mysql_operator_crds.zalando.v1",
  "classes": {
   "kubernetes:zalando.org/v1:ClusterKopfPeering": "ClusterKopfPeering",
   "kubernetes:zalando.org/v1:ClusterKopfPeeringList": "ClusterKopfPeeringList",
   "kubernetes:zalando.org/v1:ClusterKopfPeeringPatch": "ClusterKopfPeeringPatch",
   "kubernetes:zalando.org/v1:KopfPeering": "KopfPeering",
   "kubernetes:zalando.org/v1:KopfPeeringList": "KopfPeeringList",
   "kubernetes:zalando.org/v1:KopfPeeringPatch": "KopfPeeringPatch"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "mysql_operator_crds",
  "token": "pulumi:providers:kubernetes",
  "fqn": "pulumi_mysql_operator_crds",
  "class": "Provider"
 }
]
"""
)
