apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
kubernetesVersion: "v1.31.3"
nodeRegistration:
  taints: []
localAPIEndpoint:
  advertiseAddress: 192.168.200.1
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: "v1.31.3"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
kubernetesVersion: "v1.31.3"
cgroupDriver: systemd
serverTLSBootstrap: true
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
kubernetesVersion: "v1.31.3"
nodePortAddresses:
  - 127.0.0.1/32
