apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  taints: []
localAPIEndpoint:
  advertiseAddress: 192.168.99.0
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
  podSubnet: 10.250.0.0/16
controllerManager:
  extraArgs:
    port: "10252"
scheduler:
  extraArgs:
    port: "10251"
--- 
apiVersion: kubeproxy.config.k8s.io/v1alpha1  
kind: KubeProxyConfiguration  
nodePortAddresses:  
- 127.0.0.1/32
