# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_spark_operator_crds.meta as __meta
    meta = __meta
    import pulumi_spark_operator_crds.sparkoperator as __sparkoperator
    sparkoperator = __sparkoperator
else:
    meta = _utilities.lazy_import('pulumi_spark_operator_crds.meta')
    sparkoperator = _utilities.lazy_import('pulumi_spark_operator_crds.sparkoperator')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "spark_operator_crds",
  "mod": "sparkoperator.k8s.io/v1alpha1",
  "fqn": "pulumi_spark_operator_crds.sparkoperator.v1alpha1",
  "classes": {
   "kubernetes:sparkoperator.k8s.io/v1alpha1:SparkConnect": "SparkConnect",
   "kubernetes:sparkoperator.k8s.io/v1alpha1:SparkConnectList": "SparkConnectList",
   "kubernetes:sparkoperator.k8s.io/v1alpha1:SparkConnectPatch": "SparkConnectPatch"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "spark_operator_crds",
  "token": "pulumi:providers:kubernetes",
  "fqn": "pulumi_spark_operator_crds",
  "class": "Provider"
 }
]
"""
)
