# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_monitoring_crds.meta as __meta
    meta = __meta
    import pulumi_monitoring_crds.monitoring as __monitoring
    monitoring = __monitoring
else:
    meta = _utilities.lazy_import('pulumi_monitoring_crds.meta')
    monitoring = _utilities.lazy_import('pulumi_monitoring_crds.monitoring')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "monitoring_crds",
  "mod": "monitoring.coreos.com/v1",
  "fqn": "pulumi_monitoring_crds.monitoring.v1",
  "classes": {
   "kubernetes:monitoring.coreos.com/v1:PodMonitor": "PodMonitor",
   "kubernetes:monitoring.coreos.com/v1:PodMonitorList": "PodMonitorList",
   "kubernetes:monitoring.coreos.com/v1:PodMonitorPatch": "PodMonitorPatch",
   "kubernetes:monitoring.coreos.com/v1:ServiceMonitor": "ServiceMonitor",
   "kubernetes:monitoring.coreos.com/v1:ServiceMonitorList": "ServiceMonitorList",
   "kubernetes:monitoring.coreos.com/v1:ServiceMonitorPatch": "ServiceMonitorPatch"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "monitoring_crds",
  "token": "pulumi:providers:kubernetes",
  "fqn": "pulumi_monitoring_crds",
  "class": "Provider"
 }
]
"""
)
