# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_tailscale_crds.meta as __meta
    meta = __meta
    import pulumi_tailscale_crds.tailscale as __tailscale
    tailscale = __tailscale
else:
    meta = _utilities.lazy_import('pulumi_tailscale_crds.meta')
    tailscale = _utilities.lazy_import('pulumi_tailscale_crds.tailscale')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "tailscale_crds",
  "mod": "tailscale.com/v1alpha1",
  "fqn": "pulumi_tailscale_crds.tailscale.v1alpha1",
  "classes": {
   "kubernetes:tailscale.com/v1alpha1:ProxyClass": "ProxyClass",
   "kubernetes:tailscale.com/v1alpha1:ProxyClassList": "ProxyClassList",
   "kubernetes:tailscale.com/v1alpha1:ProxyClassPatch": "ProxyClassPatch"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "tailscale_crds",
  "token": "pulumi:providers:kubernetes",
  "fqn": "pulumi_tailscale_crds",
  "class": "Provider"
 }
]
"""
)
