apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.yaml: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    api:
      dashboard: true
      insecure: true
    providers:
      kubernetesCRD: {}
    certificatesResolvers:
      letsencrypt:
        acme:
          email: kevinzhenng@gmail.com
          storage: acme.json
          dnsChallenge:
            provider: cloudflare
            resolvers:
              - "1.1.1.1:53"
