apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  taints: []
  kubeletExtraArgs:
    node-ip: 192.168.0.2
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
address: 192.168.0.2
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controllerManager:
  extraArgs:
    address: 192.168.0.2
scheduler:
  extraArgs:
    address: 192.168.0.2  
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
nodePortAddresses:
- ::1/128
- 127.0.0.1/32
