apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
  labels:
    app: pong
spec:
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
      - name: pong
        image: docker.pkg.github.com/kzh/pong/pong:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pong
spec:
  selector:
    app: pong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
