apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kevinzhenng@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: kevinzhenng@gmail.com
          apiKeySecretRef:
            name: cloudflare-dns
            key: CLOUDFLARE_API_KEY
