apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: crdb-issuer
  namespace: crdb
spec:
  vault:
    path: crdb_pki/sign/crdb
    server: https://vault.vault:8200
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EVXdOakF6TURJeU0xb1hEVE14TURVd05EQXpNREl5TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGNlCk1raTVpcFZSYi9nOXFoMzFIenZsNDFuNHZscUd1cS9RRGRGaCtnNUlRWnB5S29vUW40aGVDa2wxbkIyNm5pOFMKV2VER2Y1L0V6ZGpZK1NGR2I1WnZGWHJISXNQNmZJZGRCWmN4UTlpMkwrdTNOZkUvQ0hsS0Y3Z3g0WXdRdjBhdgpHVWZRaTlnbmJJblkzVFNqUjMzblROMDhuL1F3LzE5cklFOVhUc0FEM1lJazUyZnRYSHczL2FqYmpHT3B3ZldBCkRjNnRtcS9LdUNYeWx2MGVUcDdTL2gzNVhHSjA1QnlwU2xDQUZObDlTdTZ4bExzYWFrYjN6bkNRQm9iSjJnZGsKRjFOVFdtaWphSnVEbUIraGRFdUZkUWNyakJlQ2RkTElNV0lkQnhmdStDa3V6d0hXZGFFYjRIYXgyeS9SS2dnYgpDdExicXpjRjBGd0FZdjR3eHRNQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKTzE0Nlo5QndwOE1MVDBBQ2VMSmhLVTNpbUVNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBTXdPRjFuelhReDNZT3lQdG52bTF0cjdUU2FDUEVhWjJQNDlyUytGZ1hQYmlud0RMaAp0YmFlRVJJQ2ZRQmxmRDV4Q0lLeERjZkNObkN5c0VtVDRQZDJJdVExdUpXWHV0SWlEQmZwSnZWVlRzcmJyYTlLCjZuL1lkTGsrZkpXSFlwNUh4V3d4YzlQS0ZUSFA0MklJYU44RG92WXpMOHl1cHBFeTNxT0JCazZKMTJVVDhnMDEKd3Q0WWl0eDlvQ1FXaHp6L1IxOTM0SWdyWmorREM5cncyVSsvN24wa0VDb0RCZ1hrbllSVlhkNEZsMHFTcVVYYQo2MURBSCtNRWF3dXZNdXJqUHMwMng3cFI3UHpSUkJyeWprLzJDREFZcDdJNVI1WVBYa3NqaEtyQWJnRXdtOGFaCkpSNSsrbjE0SnJKbTdqVlBzaFUzSG5wVHp6bENFVnM4Sk5pNgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    auth:
      appRole:
        path: approle
        roleId: "723500e1-549e-8136-042e-c0a84f8f9c4e"
        secretRef:
          name: crdb-approle
          key: secretId
