apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: internal
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - name: default
      hostname: "*.faust.dev"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: mtls
        options:
          gateway.istio.io/tls-terminate-mode: MUTUAL
      allowedRoutes:
        namespaces:
          from: All