apiVersion: v1
kind: Service
metadata:
  name: jellyfin-ts
  namespace: storage
  annotations:
    metallb.universe.tf/allow-shared-ip: m1-ts
spec:
  selector:
    app: jellyfin
  loadBalancerIP: 100.111.164.99
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3081
      targetPort: 8096
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: storage
spec:
  parentRefs:
    - name: internal
      namespace: istio-system
  hostnames: ["jellyfin.faust.dev"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: jellyfin
          port: 80