apiVersion: v1
kind: Service
metadata:
  name: jellyfin-lb
  namespace: storage
  annotations:
    metallb.universe.tf/allow-shared-ip: m1-ts
spec:
  selector:
    app: jellyfin
  loadBalancerIP: 100.126.227.31 
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3081
      targetPort: 8096
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jellyfin
  namespace: storage
spec:
  gateways:
  - istio-system/internal
  hosts:
  - "jellyfin.faust.dev"
  - "jf.faust.dev"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: jellyfin
