apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 195.201.53.5/32
      - 135.181.119.139/32
      - 100.126.227.31/32
      - 100.96.242.103/32
