apiVersion: v1
kind: Service
metadata:
  name: nextcloud-ts
  namespace: storage
  annotations:
    metallb.universe.tf/allow-shared-ip: m1-ts
spec:
  type: LoadBalancer
  loadBalancerIP: 100.111.164.99
  selector:
    app: nextcloud
  ports:
  - protocol: TCP
    name: http
    port: 3080
    targetPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nextcloud
  namespace: storage
spec:
  gateways:
  - istio-system/internal
  hosts:
  - "nc.faust.dev"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: nextcloud
