apiVersion: v1
kind: Namespace
metadata:
  name: pong
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
  namespace: pong
  labels:
    app: pong
spec:
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
      - name: pong
        image: docker.pkg.github.com/kzh/pong/pong:2.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pong
  namespace: pong
spec:
  selector:
    app: pong
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: pong-cert
  namespace: pong
spec:
  secretName: pong-cert
  dnsNames:
  - ping.kzh.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: pong-gateway
  namespace: pong
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: https
      number: 443
      protocol: HTTPS
    hosts:
    - "ping.kzh.dev"
    tls:
      mode: SIMPLE
      credentialName: pong-cert
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: pong
  namespace: pong
spec:
  gateways:
  - pong-gateway
  hosts:
  - "ping.kzh.dev"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: pong
