apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-mgr
  namespace: telemetry
  labels:
    release: prometheus-operator
spec:
  jobLabel: rook-ceph
  namespaceSelector:
    matchNames:
    - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook-ceph
  endpoints:
  - port: http-metrics
    interval: 5s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csi-metrics
  namespace: telemetry
  labels:
    release: prometheus-operator
spec:
  jobLabel: rook-ceph
  namespaceSelector:
    matchNames:
    - rook-ceph
  selector:
    matchLabels:
      app: csi-metrics
  endpoints:
  - port: csi-grpc-metrics
    interval: 5s
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
  namespace: telemetry
spec:
  gateways:
  - istio-system/internal
  hosts:
  - "grafana.faust.dev"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: prometheus-operator-grafana
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus
  namespace: telemetry
spec:
  gateways:
  - istio-system/internal
  hosts:
  - "prometheus.faust.dev"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 9090
        host: prometheus-operator-prometheus
