apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
  namespace: observability
  labels:
    release: prometheus-operator
spec:
  jobLabel: traefik
  podMetricsEndpoints:
  - port: traefik
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-mgr
  namespace: observability
  labels:
    release: prometheus-operator
spec:
  jobLabel: rook-ceph
  namespaceSelector:
    matchNames:
    - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook-ceph
  endpoints:
  - port: http-metrics
    interval: 5s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csi-metrics
  namespace: observability
  labels:
    release: prometheus-operator
spec:
  jobLabel: rook-ceph
  namespaceSelector:
    matchNames:
    - rook-ceph
  selector:
    matchLabels:
      app: csi-metrics
  endpoints:
  - port: csi-grpc-metrics
    interval: 5s
