apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
  namespace: storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  storageClassName: rook-cephfs
