{
 "title": "Data Dashboard",
 "tags": [ "rayVersion:2.52.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "SessionName",
    "query": {
     "query": "query_result(count by (SessionName)(last_over_time(ray_data_output_bytes{}[$__range])))"
    }
   },
   {
    "name": "DatasetID",
    "query": {
     "query": "query_result(count by (dataset)(last_over_time(ray_data_output_bytes{SessionName=~\"$SessionName\",}[$__range])))"
    }
   },
   {
    "name": "Operator",
    "query": {
     "query": "query_result(count by (operator)(last_over_time(ray_data_output_bytes{SessionName=~\"$SessionName\",}[$__range])))"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(ray_node_network_receive_speed{}, ray_io_cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes Generated by Tasks / Second",
   "type": "graph",
   "description": "Byte size of output blocks generated by tasks per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_bytes_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Bytes Generated / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Blocks Generated by Tasks / Second",
   "type": "graph",
   "description": "Number of output blocks generated by tasks per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "blocks/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_num_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Blocks Generated / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Rows Generated by Tasks / Second",
   "type": "graph",
   "description": "Number of rows in generated output blocks from finished tasks per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "rows/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_rows_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Rows Generated / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Object Store Memory",
   "type": "graph",
   "description": "Amount of memory store used by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_current_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Current Usage: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "graph",
   "description": "Number of running tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_tasks_running{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Running Tasks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Operator Combined Internal + External Input Queue Size (Blocks)",
   "type": "graph",
   "description": "Total number of blocks in operator's internal + external input queue.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "blocks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_internal_inqueue_blocks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"} + ray_data_num_external_inqueue_blocks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Combined Blocks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Operator Combined Internal + External Output Queue Size (Blocks)",
   "type": "graph",
   "description": "Total number of blocks in operator's internal + external output queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "blocks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_internal_outqueue_blocks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"} + ray_data_num_external_outqueue_blocks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Combined Blocks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Pending Inputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operator Internal Input Queue Size (Blocks)",
     "type": "graph",
     "description": "Number of blocks in operator's internal input queue",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "blocks" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_obj_store_mem_internal_inqueue_blocks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Number of Blocks: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Operator Internal Input Queue Size (Bytes)",
     "type": "graph",
     "description": "Byte size of input blocks in the operator's internal input queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_obj_store_mem_internal_inqueue{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Operator External Input Queue Size (Blocks)",
     "type": "graph",
     "description": "Number of blocks in operator's external input queue",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "blocks" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_num_external_inqueue_blocks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Number of Blocks: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Operator External Input Queue Size (bytes)",
     "type": "graph",
     "description": "Byte size of blocks in operator's external input queue",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_num_external_inqueue_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Number of Bytes: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Size of Blocks used in Pending Tasks (Bytes)",
     "type": "graph",
     "description": "Byte size of input blocks used by pending tasks.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_obj_store_mem_pending_task_inputs{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Inputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input Blocks Received by Operator / Second",
     "type": "graph",
     "description": "Number of input blocks received by operator per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "blocks/sec" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ray_data_num_inputs_received{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[1m])) by (dataset, operator)",
       "legendFormat": "Blocks Received / Second: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Input Bytes Received by Operator / Second",
     "type": "graph",
     "description": "Byte size of input blocks received by operator per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ray_data_bytes_inputs_received{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[1m])) by (dataset, operator)",
       "legendFormat": "Bytes Received / Second: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Input Blocks Processed by Tasks / Second",
     "type": "graph",
     "description": "Number of input blocks that operator's tasks have finished processing per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "blocks/sec" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ray_data_num_task_inputs_processed{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[1m])) by (dataset, operator)",
       "legendFormat": "Blocks Processed / Second: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Input Bytes Processed by Tasks / Second",
     "type": "graph",
     "description": "Byte size of input blocks that operator's tasks have finished processing per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ray_data_bytes_task_inputs_processed{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[1m])) by (dataset, operator)",
       "legendFormat": "Bytes Processed / Second: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Input Bytes Submitted to Tasks / Second",
     "type": "graph",
     "description": "Byte size of input blocks passed to submitted tasks per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ray_data_bytes_inputs_of_submitted_tasks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[1m])) by (dataset, operator)",
       "legendFormat": "Bytes Submitted / Second: {{dataset}}, {{operator}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pending Outputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operator Internal Output Queue Size (Blocks)",
     "type": "graph",
     "description": "Number of blocks in operator's internal output queue",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "blocks" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_obj_store_mem_internal_outqueue_blocks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Number of Blocks: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Operator Internal Output Queue Size (Bytes)",
     "type": "graph",
     "description": "Byte size of output blocks in the operator's internal output queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_obj_store_mem_internal_outqueue{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Operator External Output Queue Size (Blocks)",
     "type": "graph",
     "description": "Number of blocks in operator's external output queue",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "blocks" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_num_external_outqueue_blocks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Number of Blocks: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Operator External Output Queue Size (bytes)",
     "type": "graph",
     "description": "Byte size of blocks in operator's external output queue",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_num_external_outqueue_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Number of Bytes: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Max Bytes to Read",
     "type": "graph",
     "description": "Maximum bytes to read from streaming generator buffer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_max_bytes_to_read{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Max Bytes to Read: {{dataset}}, {{operator}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Outputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Size (Bytes) Histogram",
     "type": "graph",
     "description": "Size (in bytes) per block. Larger bars means more blocks are within that size range.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (le) (max_over_time(ray_data_block_size_bytes_bucket{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\", le!=\"+Inf\"}[$__range]))",
       "legendFormat": "{{le}} bytes"
      }
     ]
    },
    {
     "title": "Block Size (Rows) Histogram",
     "type": "graph",
     "description": "Number of rows per block. Larger bars means more blocks are within that number of rows range.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (le) (max_over_time(ray_data_block_size_rows_bucket{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\", le!=\"+Inf\"}[$__range]))",
       "legendFormat": "{{le}} rows"
      }
     ]
    },
    {
     "title": "Output Blocks Taken by Downstream Operators / Second",
     "type": "graph",
     "description": "Number of output blocks taken by downstream operators per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "yaxes": [
      { "format": "blocks/sec" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ray_data_num_outputs_taken{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[1m])) by (dataset, operator)",
       "legendFormat": "Blocks Taken / Second: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Output Bytes Taken by Downstream Operators / Second",
     "type": "graph",
     "description": "Byte size of output blocks taken by downstream operators per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ray_data_bytes_outputs_taken{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[1m])) by (dataset, operator)",
       "legendFormat": "Bytes Taken / Second: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Output Bytes from Finished Tasks / Second (by Node)",
     "type": "graph",
     "description": "Byte size of output blocks from finished tasks per second, grouped by node.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ray_data_bytes_outputs_of_finished_tasks_per_node{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}[1m])) by (dataset, node_ip)",
       "legendFormat": "Bytes output / Second: {{dataset}}, {{node_ip}}"
      }
     ]
    },
    {
     "title": "Blocks from Finished Tasks / Second (by Node)",
     "type": "graph",
     "description": "Number of output blocks from finished tasks per second, grouped by node.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
     "yaxes": [
      { "format": "blocks/s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ray_data_blocks_outputs_of_finished_tasks_per_node{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}[1m])) by (dataset, node_ip)",
       "legendFormat": "Blocks output / Second: {{dataset}}, {{node_ip}}"
      }
     ]
    },
    {
     "title": "Bytes Output / Second",
     "type": "graph",
     "description": "Bytes output per second by dataset operators.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ray_data_output_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[1m])) by (dataset, operator)",
       "legendFormat": "Bytes Output / Second: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Rows Output / Second",
     "type": "graph",
     "description": "Total rows output per second by dataset operators.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
     "yaxes": [
      { "format": "rows/sec" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ray_data_output_rows{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[1m])) by (dataset, operator)",
       "legendFormat": "Rows Output / Second: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Average Bytes Generated / Output Block",
     "type": "graph",
     "description": "Average byte size of output blocks generated by tasks.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "increase(ray_data_bytes_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[5m]) / increase(ray_data_num_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[5m])",
       "legendFormat": "Average Bytes Generated / Output Block: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Average Number of Output Blocks / Task",
     "type": "graph",
     "description": "Average number of output blocks generated by tasks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
     "yaxes": [
      { "format": "blocks" }
     ],
     "targets": [
      {
       "expr": "increase(ray_data_num_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[5m]) / increase(ray_data_num_tasks_finished{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[5m])",
       "legendFormat": "Average Number of Output Blocks / Task: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Block Generation Time",
     "type": "graph",
     "description": "Time spent generating blocks in tasks.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(ray_data_block_generation_time{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[5m]) / increase(ray_data_num_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[5m])",
       "legendFormat": "Block Generation Time: {{dataset}}, {{operator}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Completion Time Histogram (s)",
     "type": "graph",
     "description": "Time (in seconds) spent (including backpressure) running tasks to completion. Larger bars means more tasks finished within that duration range.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (le) (max_over_time(ray_data_task_completion_time_bucket{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\", le!=\"+Inf\"}[$__range]))",
       "legendFormat": "{{le}} s"
      }
     ]
    },
    {
     "title": "Block Completion Time Histogram (s)",
     "type": "graph",
     "description": "Time (in seconds) spent processing blocks to completion. If multiple blocks are generated per task, this is approximated by assuming each block took an equal amount of time to process. Larger bars means more blocks finished within that duration range.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (le) (max_over_time(ray_data_block_completion_time_bucket{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\", le!=\"+Inf\"}[$__range]))",
       "legendFormat": "{{le}} s"
      }
     ]
    },
    {
     "title": "Task Completion Time Without Backpressure",
     "type": "graph",
     "description": "Time spent running tasks to completion w/o backpressure.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(ray_data_task_completion_time_without_backpressure{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[5m]) / increase(ray_data_num_tasks_finished{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[5m])",
       "legendFormat": "Task Completion Time w/o Backpressure: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Task Output Backpressure Time",
     "type": "graph",
     "description": "Time spent in output backpressure.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(ray_data_task_output_backpressure_time{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[5m]) / increase(ray_data_num_tasks_finished{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[5m])",
       "legendFormat": "Task Output Backpressure Time: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Task Submission Backpressure Time",
     "type": "graph",
     "description": "Time spent in task submission backpressure.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(ray_data_task_submission_backpressure_time{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[5m]) / increase(ray_data_num_tasks_submitted{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}[5m])",
       "legendFormat": "Backpressure Time: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Task Throughput (by Node)",
     "type": "graph",
     "description": "Number of finished tasks per second, grouped by node.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
     "yaxes": [
      { "format": "tasks/s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ray_data_num_tasks_finished_per_node{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}[1m])) by (dataset, node_ip)",
       "legendFormat": "Finished Tasks: {{dataset}}, {{node_ip}}"
      }
     ]
    },
    {
     "title": "Tasks with output blocks",
     "type": "graph",
     "description": "Number of tasks that already have output.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
     "yaxes": [
      { "format": "tasks" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_num_tasks_have_outputs{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Tasks with output blocks: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Submitted Tasks",
     "type": "graph",
     "description": "Number of submitted tasks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
     "yaxes": [
      { "format": "tasks" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_num_tasks_submitted{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Submitted Tasks: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Finished Tasks",
     "type": "graph",
     "description": "Number of finished tasks.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
     "yaxes": [
      { "format": "tasks" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_num_tasks_finished{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Finished Tasks: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Failed Tasks",
     "type": "graph",
     "description": "Number of failed tasks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 190 },
     "yaxes": [
      { "format": "tasks" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_num_tasks_failed{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Failed Tasks: {{dataset}}, {{operator}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Budget / Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logical Slots Being Used (CPU)",
     "type": "graph",
     "description": "Logical CPUs currently being used by dataset operators.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 199 },
     "yaxes": [
      { "format": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_cpu_usage_cores{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "CPU Usage: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Logical Slots Being Used (GPU)",
     "type": "graph",
     "description": "Logical GPUs currently being used by dataset operators.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 199 },
     "yaxes": [
      { "format": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_gpu_usage_cores{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "GPU Usage: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Budget (CPU)",
     "type": "graph",
     "description": "Budget (CPU) for the operator.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 207 },
     "yaxes": [
      { "format": "cpu" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_cpu_budget{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Budget (CPU): {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Budget (GPU)",
     "type": "graph",
     "description": "Budget (GPU) for the operator.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 207 },
     "yaxes": [
      { "format": "gpu" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_gpu_budget{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Budget (GPU): {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Budget (Memory)",
     "type": "graph",
     "description": "Budget (Memory) for the operator.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 215 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_memory_budget{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Budget (Memory): {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Budget (Object Store Memory)",
     "type": "graph",
     "description": "Budget (Object Store Memory) for the operator.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 215 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_object_store_memory_budget{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Budget (Object Store Memory): {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Freed Memory in Object Store (Bytes)",
     "type": "graph",
     "description": "Byte size of freed memory in object store.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 223 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_obj_store_mem_freed{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Spilled Memory in Object Store (Bytes)",
     "type": "graph",
     "description": "Byte size of spilled memory in object store.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 223 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_obj_store_mem_spilled{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Bytes Spilled",
     "type": "graph",
     "description": "Amount spilled by dataset operators. DataContext.enable_get_object_locations_for_metrics must be set to True to report this metric",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 231 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_spilled_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Bytes Spilled: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Bytes Freed",
     "type": "graph",
     "description": "Amount freed by dataset operators.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 231 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_freed_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "Bytes Freed: {{dataset}}, {{operator}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduling Loop",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 239 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduling Loop Duration",
     "type": "graph",
     "description": "Duration of the scheduling loop in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 240 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_sched_loop_duration_s{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (dataset)",
       "legendFormat": "Scheduling Loop Duration: {{dataset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Iteration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 248 },
   "collapsed": true,
   "panels": [
    {
     "title": "Iteration Initialization Time",
     "type": "graph",
     "description": "Seconds spent in iterator initialization code",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_iter_initialize_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (dataset)",
       "legendFormat": "Seconds: {{dataset}}, {{operator}}"
      }
     ]
    },
    {
     "title": "Iteration Blocked Time",
     "type": "graph",
     "description": "Seconds user thread is blocked by iter_batches()",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_iter_total_blocked_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (dataset)",
       "legendFormat": "Seconds: {{dataset}}"
      }
     ]
    },
    {
     "title": "Iteration User Time",
     "type": "graph",
     "description": "Seconds spent in user code",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_iter_user_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (dataset)",
       "legendFormat": "Seconds: {{dataset}}"
      }
     ]
    },
    {
     "title": "Iteration Get Time",
     "type": "graph",
     "description": "Seconds spent in ray.get() while resolving block references",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "yaxes": [
      { "format": "seconds" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_iter_get_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (dataset)",
       "legendFormat": "Seconds: {{dataset}}"
      }
     ]
    },
    {
     "title": "Iteration Next Batch Time",
     "type": "graph",
     "description": "Seconds spent getting the next batch from the block buffer",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "yaxes": [
      { "format": "seconds" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_iter_next_batch_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (dataset)",
       "legendFormat": "Seconds: {{dataset}}"
      }
     ]
    },
    {
     "title": "Iteration Format Batch Time",
     "type": "graph",
     "description": "Seconds spent formatting the batch",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
     "yaxes": [
      { "format": "seconds" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_iter_format_batch_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (dataset)",
       "legendFormat": "Seconds: {{dataset}}"
      }
     ]
    },
    {
     "title": "Iteration Collate Batch Time",
     "type": "graph",
     "description": "Seconds spent collating the batch",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
     "yaxes": [
      { "format": "seconds" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_iter_collate_batch_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (dataset)",
       "legendFormat": "Seconds: {{dataset}}"
      }
     ]
    },
    {
     "title": "Iteration Finalize Batch Time",
     "type": "graph",
     "description": "Seconds spent finalizing the batch",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 273 },
     "yaxes": [
      { "format": "seconds" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_iter_finalize_batch_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (dataset)",
       "legendFormat": "Seconds: {{dataset}}"
      }
     ]
    },
    {
     "title": "Iteration Blocks Local",
     "type": "graph",
     "description": "Number of blocks already on the local node",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 281 },
     "yaxes": [
      { "format": "blocks" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_iter_blocks_local{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (dataset)",
       "legendFormat": "Blocks: {{dataset}}"
      }
     ]
    },
    {
     "title": "Iteration Blocks Remote",
     "type": "graph",
     "description": "Number of blocks that require fetching from another node",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 281 },
     "yaxes": [
      { "format": "blocks" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_iter_blocks_remote{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (dataset)",
       "legendFormat": "Blocks: {{dataset}}"
      }
     ]
    },
    {
     "title": "Iteration Blocks Unknown Location",
     "type": "graph",
     "description": "Number of blocks that have unknown locations",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 289 },
     "yaxes": [
      { "format": "blocks" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_iter_unknown_location{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (dataset)",
       "legendFormat": "Blocks: {{dataset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operator Panels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 297 },
   "collapsed": true,
   "panels": [
    {
     "title": "All logical resources utilization",
     "type": "graph",
     "description": "Shows all logical resources utilization on a single graph. Filtering by operator is recommended.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 298 },
     "yaxes": [
      { "format": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(ray_data_cpu_usage_cores{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "CPU: {{dataset}}, {{operator}}"
      },
      {
       "expr": "sum(ray_data_gpu_usage_cores{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\", operator=~\"$Operator\"}) by (dataset, operator)",
       "legendFormat": "GPU: {{dataset}}, {{operator}}"
      }
     ]
    }
   ]
  }
 ]
}