image:
  repository: cockroachdb/cockroach
  tag: v24.3.0

conf:
  single-node: true
  max-sql-memory: 8G
  cache: 8G

statefulset:
  replicas: 1

tls:
  enabled: false

service:
  public:
    annotations:
      tailscale.com/expose: "true"
      tailscale.com/hostname: cockroachdb-public

storage:
  persistentVolume:
    size: 100Gi
