image:
  repository: cockroachdb/cockroach
  tag: v23.1.11

tls:
  certs:
    certManager: true
    useCertManagerV1CRDs: true
    certManagerIssuer:
      name: crdb-issuer
      kind: ClusterIssuer
      nodeCertDuration: 4380h
      isSelfSignedIssuer: false
    tlsSecret: true
    selfSigner:
      enabled: false

storage:
  persistentVolume:
    size: 200Gi

statefulset:
  resources:
    requests:
      memory: 6Gi
      cpu: 400m