[project]
name = "stitch"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-command>=1.1.0",
    "pulumi-kubernetes>=4.0.0,<5.0.0",
    "pulumi-postgresql>=3.15.2",
    "pulumi-random>=4.18.2",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
